### ISSUE TITLE
About the repo sync

### ISSUE THREAD

**Issue by showp1874** [AospExtended/manifest#15]
When i Syncing the source，and the following error occurs：
fatal: repository 'https://www.codeaurora.org/quic/la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/' not found

fatal: repository 'https://www.codeaurora.org/quic/la/platform/packages/apps/SoundRecorder/' not found

fatal: repository 'https://www.codeaurora.org/quic/la/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/' not found

**Comment by ishubhamsingh** [comment]
Strange,i just tried a sync and didn't faced any issues.

**Comment by arbazkhan444** [comment]
same Fatal: repository not found error ..how to fix this
