### ISSUE TITLE
Suddenly reboot

### ISSUE THREAD

**Issue by carlosmqz** [AospExtended/manifest#23]
I was playing a game then  the phone rebooted out of nowhere, here's part of the log
11-02 21:28:20.106 E/ActivityThread(1937): Service com.google.android.gms.chimera.PersistentBoundBrokerService has leaked IntentReceiver ahmj@a9fa999 that was originally registered here. Are you missing a call to unregisterReceiver()?

11-02 21:28:20.106 E/ActivityThread(1937): android.app.IntentReceiverLeaked: Service com.google.android.gms.chimera.PersistentBoundBrokerService has leaked IntentReceiver ahmj@a9fa999 that was originally registered here. Are you missing a call to unregisterReceiver()?

11-02 21:28:20.106 E/ActivityThread(1937): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)

**Comment by ghost** [comment]
Report that to your maintainer on thread not here. Doesn't happens on other device so it is device related issue.
