### ISSUE TITLE
lunch problem

### ISSUE THREAD

**Issue by SMARTSKA97** [AospExtended/manifest#24]
i have completely synced the repo, git cloned the device tree - land(Redmi 3s Prime), yet i cannot 'lunch' it... it shows the following error...
------------------------------------------------------------------------------------------------------------------------------------------
build/core/envsetup.mk:220: *** Unsupported option MALLOC_IMPL defined by board config: device/xiaomi/land/BoardConfig.mk.
build/core/envsetup.mk:221: *** Use `MALLOC_SVELTE := true` to configure jemalloc for low-memory.  Stop.
build/core/envsetup.mk:220: *** Unsupported option MALLOC_IMPL defined by board config: device/xiaomi/land/BoardConfig.mk.
build/core/envsetup.mk:221: *** Use `MALLOC_SVELTE := true` to configure jemalloc for low-memory.  Stop.
Device land not found. Attempting to retrieve device repository from AospExtended-Devices Github (http://github.com/AospExtended-Devices).
Repository for land not found in the AospExtended-Devices Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/aex_manifest.xml
build/core/envsetup.mk:220: *** Unsupported option MALLOC_IMPL defined by board config: device/xiaomi/land/BoardConfig.mk.
build/core/envsetup.mk:221: *** Use `MALLOC_SVELTE := true` to configure jemalloc for low-memory.  Stop.
----------------------------------------------------------------------------------------------------------------------------------------
what could be the error, please guide me as there is no perfect tutorial(even googling didn't helped either)...
also, if possible can you provide complete tutorial... i want to learn...
Thanks in advance...

**Comment by ghost** [comment]
Go to your device/xiaomi/land and remove the line 220. That function there is unsupported, so remove the line. BTW this ain't ROM issue. Close this issue after you fix it. You can better ask issues on telegram group of AEX.

**Comment by SMARTSKA97** [comment]
can you provide the link??? thanks in advance...
