### ISSUE TITLE
macOS grep : (23) Failed writing body

### ISSUE THREAD

**Issue by kholisrag** [AospExtended/manifest#25]
I want to build android ROM from source in macOS 10.13.2

I'm done with `repo sync` and excute the . build/envsetup.sh

but there is an output stderr : 

> including device/generic/mini-emulator-mips/vendorsetup.sh
> including device/generic/mini-emulator-mips64/vendorsetup.sh
> including vendor/aosp/vendorsetup.sh
> usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
> 	[-e pattern] [-f file] [--binary-files=value] [--color=when]
> 	[--context[=num]] [--directories=action] [--label] [--line-buffered]
> 	[--null] [pattern] [file ...]
> (23) Failed writing body
> including sdk/bash_completion/adb.bash

I trace the problem... I assume it's because the curl and grep is not compatible...

the code ins vendor/aosp/vendorsetup.sh is like this...

for device in $(curl -s https://raw.githubusercontent.com/AospExtended/official_devices/master/devices.json | sed 's/ //; /^$/d' | grep -Po '\"codename\": ".*?"' | sed -e 's/codename//;s/\"//g;s/\: //')
 do for var in eng user userdebug;
    do
      add_lunch_combo aosp_$device-$var
    done
 done

Anyone can help?

**Comment by RainSnowZ** [comment]
Hey , Boy.There are many problems in building AospExtended on MacOS 10.13.I also builded , but it was failed. The best way to solve this problem is using Ubuntu to build AospExtended.
Good luch and have a good time.

**Comment by kholisrag** [comment]
That's help full info...
Thanks for the answer....
In that case, I just to create Ubuntu VM
