### ISSUE TITLE
Screenrecord Sound doesn't record

### ISSUE THREAD

**Issue by celu** [AospExtended/manifest#27]
When you récord the screen with the notifications long press screen record the audio that you are playing on the phone doesnt record

**Comment by ishubhamsingh** [comment]
It's screen recorder, not sound recorder.

**Comment by celu** [comment]
But other ROMs also record the sound with the screen, this ROM doesn't you could vive the possibility

**Comment by ishubhamsingh** [comment]
You can use 3rd party apps for that.

**Comment by celu** [comment]
And why not add to the ROM?
