### ISSUE TITLE
Missing repository referenced during repo sync of 7.1.1

### ISSUE THREAD

**Issue by PeterHindes** [AospExtended/manifest#29]
the repository https://github.com/AospExtended/packages_apps_SnapdragonCamera/ is a 404 not found, and prevents this branch from repo syncing properly

**Comment by ghost** [comment]
Use this https://github.com/AospExtended/platform_packages_apps_Snap 
and build **Snap**

**Comment by ishubhamsingh** [comment]
@PeterHindes Which branch are you using? 8.1.x branch is the one you should use for oreo and 7.x for nougat, rest all are deprecated.

**Comment by PeterHindes** [comment]
ok, I was trying to use 7.1.1 Is 7.x the most up to date? what version is the x currently in 7.x?

**Comment by PeterHindes** [comment]
also unrelated but the xml for Z00T is missing a coma and there is no issues tab on that repository, and I was wondering if the "aex" branch there was for 7.x?

**Comment by ishubhamsingh** [comment]
@PeterHindes yes 7.x is the most up-to-date branch for nougat. It is 7.1.2 with March 2018 security patch merged.

**Comment by PeterHindes** [comment]
ok, thanks

**Comment by PeterHindes** [comment]
I am currently trying to build 7.x for the Z00T but it seems the branch for 7.x is non existent for Z00T. What is the normal method for building 7.x on other devices, or the Z00T?

**Comment by ghost** [comment]
It is missing because I deleted it. If you need sources, clone them manually from my profile. BTW I am your **Z00T** maintainer. In case of any issue, ping me on [telegram](https://t.me/theimpulson)

**Comment by PeterHindes** [comment]
ok thanks, just wondering though, why did you delete the 7.x branch?

**Comment by PeterHindes** [comment]
issue will not be fixed, that branch is unsupported and the incorrect version
