### ISSUE TITLE
Can't compile for device Osprey

### ISSUE THREAD

**Issue by Peque** [AospExtended/manifest#30]
Using a clean setup (Docker image with required dependencies installed). After successfully running:

```
repo init -u git://github.com/AospExtended/manifest.git -b 8.1.x
repo sync -c -j16 --force-sync --no-clone-bundle --no-tags
source build/envsetup.sh
lunch aosp_osprey-user
```

I then try to compile with:

```
mka aex -j5
```

With the following error:

> **/home/build/android/prebuilts/gcc/linux-x86/arm/arm-eabi-7.2/bin/arm-eabi-gcc failed: No such file or directory**

I have seen version `7.2` is hardcoded in the [`device/motorola/osprey/BoardConfig.mk`](https://github.com/AospExtended-Devices/device_motorola_osprey) but that version is not listed under my local `android/prebuilts/gcc/linux-x86/arm/` folder.

If I try to change that `BoardConfig.mk` file to use `4.8`, which is the version I have available in my `prebuilts/` local folder, then I get a new error:

> **arm-eabi-gcc: error: unrecognized command line option '-fstack-protector-strong'**

How could I workaround this? Can you reproduce the issue?

**Comment by ishubhamsingh** [comment]
just comment out that line or just put linaro gcc 7.2 into prebuilts/gcc/linux-x86/arm/arm-eabi-7.2

**Comment by Peque** [comment]
@ishubhamsingh Thanks for your quick reply.

Should not this work just fine out-the-box? Or have those instructions you gave me documented somewhere? Should that line be removed then from the `BoardConfig.mk` file in the Osprey repository? :blush:

I will try commenting that line and reply back with the results, thanks for the hint.

I guess the fact that I do have `4.8` available in my `prebuilts/` folder is because there is some configuration file that ensures that version is downloaded automatically before build. Rather than manually download version `7.2` should not I be able to simply change a configuration file to specify which `arm-eabi` compiler to download?

**Comment by Peque** [comment]
@ishubhamsingh Yeah, having `7.2` in my prebuilts folder allows for a successful compilation. I still wonder, should not this be automatic without requiring the user to manually download any dependencies?

Anyway after flashing the ROM it got stuck with a completely black screen (it is turned on, but all black and apparently not responding to any input). So not a successful experiment after all... :sweat:
