### ISSUE TITLE
Cast doesn't work

### ISSUE THREAD

**Issue by Jarvi5x01** [AospExtended/manifest#32]
AEX (mido Oreo) Issue report:- Everytime I try to cast my device to certain device (in my case, laptop) It shows up in devices list, but when clicked on it... It disappears and after couple of seconds the device again shows up & the cyxle continues. Confirmed working of functionality on Laptop through casting Redmi Note 4G (a 6 year old phone running kitkat)

**Comment by ghost** [comment]
That's a device specific issue first of all. You should report it on XDA Thread or open issue in device specific repo. Also cast works fine on other mido devices. Please provide steps to reproduce bugs and give logcats next time. You can close this issue.

**Comment by Jarvi5x01** [comment]
Ok. Will provide steps to recreate on XDA thread.
