### ISSUE TITLE
No makefile for aosp_device_kenzo

### ISSUE THREAD

**Issue by OmerFlame** [AospExtended/manifest#37]
Hi,

I'm trying to build AOSP Extended for Xiaomi Redmi Note 3 (kenzo) manually, and I'm facing a problem: the script says it cannot find a makefile for aosp_device_kenzo. What do I do in this situation?

BTW, I checked at the official devices list, and kenzo DOES show up. Help, please!

**Comment by ghost** [comment]
This is not an issue. You just don't know how to build a ROM. Use trees from @AmolAmrit 's repo or contact him for help.

**Comment by OmerFlame** [comment]
Okay, I found the repository with the makefiles and everything. I can't find help (I need to build asap but Amol is not answering), so can you help me?

P.S. you said it a bit rude, that I don't know how to build a ROM. I really don't know, this is the first ROM I'm building. Just bear with me. I'm trying to figure things out by just exploring directories. I'm completely new to building ROMs.

**Comment by laijirong** [comment]
Install All dependeces，sync trees vendor kernel，./build/envsetup.sh
lunch
entering your codename
mka aex -jx
output files can be found in out under source dir.
->repo:{mkdir ~/bin
PATH=~/bin:$PATH
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo}

->.bashrc:{alias repo="~/bin/repo"
export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'
export USE_CCACHE=1
prebuilts/misc/linux-x86/ccache/ccache -M 50G
export CCACHE_COMPRESS=1
export ANDROID_JACK_VM_ARGS="-Xmx8g -Dfile.encoding=UTF-8 -XX:+TieredCompilation"}

->source:{repo init -u https://github.com/aosp-mirror/platform_manifest.git}

->lunch:{. build/envsetup.sh
brunch <_codename>}

->openJDK 配置环境变量方法:{1.用gedit文本编辑器在/etc/profile中添加环境变量：
命令 ： sudo gedit /etc/profile
2.在打开的/etc/profile文件末尾添加下面几行：
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=${JAVA_HOME}/bin:$PATH}
(poor English)

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: OmerFlame <notifications@github.com>
发送时间: Wednesday, November 14, 2018 2:17:26 AM
收件人: AospExtended/manifest
抄送: Subscribed
主题: Re: [AospExtended/manifest] No makefile for aosp_device_kenzo (#37)


Okay, I found the repository with the makefiles and everything. I can't find help (I need to build asap but Amol is not answering), so can you heelp me?

P.S. you said it a bit rude, that I don't know how to build a ROM. I really don't know, this is the first ROM I'm building. Just bear with me. I'm trying to figure things out by just exploring directories. I'm completely new to building ROMs.

―
