### ISSUE TITLE
Build Bug

### ISSUE THREAD

**Issue by ShihabZzz** [AospExtended/manifest#47]
https://del.dog/ajosajogad.sql

mka bacon
============================================
                                            
          ▄▄▄      ▓█████ ▒██   ██▒         
         ▒████▄    ▓█   ▀ ▒▒ █ █ ▒░         
         ▒██  ▀█▄  ▒███   ░░  █   ░         
         ░██▄▄▄▄██ ▒▓█  ▄  ░ █ █ ▒          
          ▓█   ▓██▒░▒████▒▒██▒ ▒██▒         
          ▒▒   ▓▒█░░░ ▒░ ░▒▒ ░ ░▓ ░         
           ▒   ▒▒ ░ ░ ░  ░░░   ░▒ ░         
           ░   ▒      ░    ░    ░           
               ░  ░   ░  ░ ░    ░           
                                            
        AospExtended-v6.4 9 
============================================
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
EXTENDED_MOD_VERSION=AospExtended-v6.4-20190415-0352-UNOFFICIAL
TARGET_PRODUCT=aosp_markw
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-1029-gcp-x86_64-Ubuntu-18.04.2-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ2A.190405.003
OUT_DIR=/home/shihab_riadn/aex/out
PRODUCT_SOONG_NAMESPACES= hardware/qcom/audio-caf/msm8996 hardware/qcom/display-caf/msm8996 hardware/qcom/media-caf/msm8996
============================================
ninja: no work to do.
ninja: no work to do.
Environment variable BUILD_NUMBER was modified (a42d69fa55 => b88de02a01), regenerating...
Environment variable BUILD_NUMBER was modified (a42d69fa55 => b88de02a01), regenerating...
[25/1075] including development/build/Android.mk ...
development/build/build_android_stubs.mk:43: warning: android_stubs_current 
development/build/build_android_stubs.mk:43: warning: metalava_android_stubs_current metalava_android_stubs_current
development/build/build_android_stubs.mk:43: warning: android_system_stubs_current 
development/build/build_android_stubs.mk:43: warning: android_test_stubs_current 
development/build/build_android_stubs.mk:43: warning: metalava_android_system_stubs_current metalava_android_system_stubs_current
development/build/build_android_stubs.mk:43: warning: metalava_android_test_stubs_current metalava_android_test_stubs_current
[113/1075] including device/xiaomi/markw/Android.mk ...
device/xiaomi/markw/vndk/Android.mk:2: warning: ************* BOARD VNDK is not enabled - compiling vndk-sp ***************************
[600/1075] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:88: warning: Be careful when using the SELINUX_IGNORE_NEVERALLOWS flag. It does not work in user builds and using it will not stop you from failing CTS.
[1075/1075] including vendor/xiaomi/msm8953-common/Android.mk ...
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libjni_latinime.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libjni_latinime.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/etc/seccomp_policy/configstore@1.1.policy'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/etc/seccomp_policy/configstore@1.1.policy'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libaacwrapper.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libaacwrapper.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libfilterfw.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libfilterfw.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libfilterpack_imageproc.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libfilterpack_imageproc.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libldacBT_abr.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libldacBT_abr.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libldacBT_enc.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libldacBT_enc.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libstagefright_soft_flacdec.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib/libstagefright_soft_flacdec.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libfilterfw.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libfilterfw.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libfilterpack_imageproc.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libfilterpack_imageproc.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libldacBT_abr.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libldacBT_abr.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libldacBT_enc.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/system/lib64/libldacBT_enc.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/bin/wcnss_service'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/bin/wcnss_service'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/lib/hw/thermal.msm8953.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/lib/hw/thermal.msm8953.so'
build/make/core/Makefile:40: warning: overriding commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/lib64/hw/thermal.msm8953.so'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `/home/shihab_riadn/aex/out/target/product/markw/vendor/lib64/hw/thermal.msm8953.so'
[  0% 10/1624] Target buildinfo: /home/shihab_riadn/aex/out/target/product/markw/obj/ETC/system_build_prop_intermediates/build.prop
Target buildinfo from: device/xiaomi/markw/system.prop
[  1% 27/1624] Building Kernel Config
make: Entering directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
  GEN     ./Makefile
#
# configuration written to .config
#
make[1]: Leaving directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
make: Entering directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --savedefconfig=defconfig Kconfig
make[1]: Leaving directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
[  3% 49/1624] Proguard: /home/shihab_riadn/aex/out/target/common/obj/APPS/OneTimeInitializer_intermediates/classes-proguard.jar
ProGuard, version 5.1
Reading input...
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android_stubs_current_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar]
Reading program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/OneTimeInitializer_intermediates/classes.jar]
Initializing...
Ignoring unused library classes...
  Original number of library classes: 15763
  Final number of library classes:    15763
Shrinking...
Removing unused program classes and class elements...
  Original number of program classes: 99
  Final number of program classes:    17
Writing output...
Preparing output jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/OneTimeInitializer_intermediates/classes-proguard.jar]
  Copying resources from program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/OneTimeInitializer_intermediates/classes.jar]
[  3% 55/1624] target dex2oat: /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm/boot.art
FAILED: /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm/boot.art 
/bin/bash -c "(mkdir -p /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm/ ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm//*.art /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm//*.oat /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm//*.art.rel ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm//*.art ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm//*.oat ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm//*.art.rel ) && (ANDROID_LOG_TAGS=\"*:e\" /home/shihab_riadn/aex/out/host/linux-x86/bin/dex2oat --runtime-arg -Xms64m           --runtime-arg -Xmx64m           --compiler-filter=speed-profile --profile-file=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/boot.prof          --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/conscrypt_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/bouncycastle_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/voip-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ims-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android.hidl.base-V1.0-java_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android.hidl.manager-V1.0-java_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework-oahl-backward-compatibility_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android.test.base_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/telephony-ext_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/qti-telephony-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/WfdCommon_intermediates/javalib.jar          --dex-location=/system/framework/core-oj.jar --dex-location=/system/framework/core-libart.jar --dex-location=/system/framework/conscrypt.jar --dex-location=/system/framework/okhttp.jar --dex-location=/system/framework/bouncycastle.jar --dex-location=/system/framework/apache-xml.jar --dex-location=/system/framework/ext.jar --dex-location=/system/framework/framework.jar --dex-location=/system/framework/telephony-common.jar --dex-location=/system/framework/voip-common.jar --dex-location=/system/framework/ims-common.jar --dex-location=/system/framework/android.hidl.base-V1.0-java.jar --dex-location=/system/framework/android.hidl.manager-V1.0-java.jar --dex-location=/system/framework/framework-oahl-backward-compatibility.jar --dex-location=/system/framework/android.test.base.jar --dex-location=/system/framework/telephony-ext.jar --dex-location=/system/framework/qti-telephony-common.jar --dex-location=/system/framework/WfdCommon.jar            --oat-symbols=/home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm/boot.oat             --oat-file=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm/boot.oat           --oat-location=/system/framework/arm/boot.oat                 --image=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm/boot.art --base=0x70000000            --instruction-set=arm           --instruction-set-variant=cortex-a53          --instruction-set-features=default              --android-root=/home/shihab_riadn/aex/out/target/product/markw/system           --runtime-arg -Xnorelocate --compile-pic                --no-generate-debug-info --generate-build-id --multi-image --no-inline-from=core-oj.jar               --abort-on-hard-verifier-error          --abort-on-soft-verifier-error                          || ( echo \"ERROR: Dex2oat failed to compile a boot image. It is likely that the boot classpath is inconsistent. Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS=\"--runtime-arg -verbose:verifier\" to see verification errors.\" ; false ) &&        ANDROID_LOG_TAGS=\"*:e\" ANDROID_ROOT=/home/shihab_riadn/aex/out/target/product/markw/system ANDROID_DATA=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm/ /home/shihab_riadn/aex/out/host/linux-x86/bin/patchoat           --input-image-location=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/boot.art                 --output-image-relocation-directory=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm/          --instruction-set=arm           --base-offset-delta=0x10000000 )"
dex2oat F 04-15 03:54:43  4945  4945 compiler_driver.cc:942] Had 2 soft failure(s) verifying all classes, and was asked to abort in such situations. Please check the log.
ERROR: Dex2oat failed to compile a boot image. It is likely that the boot classpath is inconsistent. Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS=--runtime-arg -verbose:verifier to see verification errors.
[  3% 57/1624] target dex2oat: /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64/boot.art
FAILED: /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64/boot.art 
/bin/bash -c "(mkdir -p /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm64/ ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64//*.art /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64//*.oat /home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64//*.art.rel ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm64//*.art ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm64//*.oat ) && (rm -f /home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm64//*.art.rel ) && (ANDROID_LOG_TAGS=\"*:e\" /home/shihab_riadn/aex/out/host/linux-x86/bin/dex2oat --runtime-arg -Xms64m             --runtime-arg -Xmx64m           --compiler-filter=speed-profile --profile-file=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/boot.prof       --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/conscrypt_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/bouncycastle_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/voip-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ims-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android.hidl.base-V1.0-java_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android.hidl.manager-V1.0-java_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework-oahl-backward-compatibility_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android.test.base_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/telephony-ext_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/qti-telephony-common_intermediates/javalib.jar --dex-file=/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/WfdCommon_intermediates/javalib.jar             --dex-location=/system/framework/core-oj.jar --dex-location=/system/framework/core-libart.jar --dex-location=/system/framework/conscrypt.jar --dex-location=/system/framework/okhttp.jar --dex-location=/system/framework/bouncycastle.jar --dex-location=/system/framework/apache-xml.jar --dex-location=/system/framework/ext.jar --dex-location=/system/framework/framework.jar --dex-location=/system/framework/telephony-common.jar --dex-location=/system/framework/voip-common.jar --dex-location=/system/framework/ims-common.jar --dex-location=/system/framework/android.hidl.base-V1.0-java.jar --dex-location=/system/framework/android.hidl.manager-V1.0-java.jar --dex-location=/system/framework/framework-oahl-backward-compatibility.jar --dex-location=/system/framework/android.test.base.jar --dex-location=/system/framework/telephony-ext.jar --dex-location=/system/framework/qti-telephony-common.jar --dex-location=/system/framework/WfdCommon.jar            --oat-symbols=/home/shihab_riadn/aex/out/target/product/markw/symbols/system/framework/arm64/boot.oat           --oat-file=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64/boot.oat               --oat-location=/system/framework/arm64/boot.oat                 --image=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64/boot.art --base=0x70000000          --instruction-set=arm64              --instruction-set-variant=cortex-a53             --instruction-set-features=default              --android-root=/home/shihab_riadn/aex/out/target/product/markw/system           --runtime-arg -Xnorelocate --compile-pic                --no-generate-
debug-info --generate-build-id          --multi-image --no-inline-from=core-oj.jar              --abort-on-hard-verifier-error          --abort-on-soft-verifier-error                          || ( echo \"ERROR: Dex2oat failed to compile a boot image. It is likely that the boot classpath is inconsistent. Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS=\"--runtime-arg -verbose:verifier\" to see verification errors.\" ; false ) &&        ANDROID_LOG_TAGS=\"*:e\" ANDROID_ROOT=/home/shihab_riadn/aex/out/target/product/markw/system ANDROID_DATA=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64/ /home/shihab_riadn/aex/out/host/linux-x86/bin/patchoat                 --input-image-location=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/boot.art                 --output-image-relocation-directory=/home/shihab_riadn/aex/out/target/product/markw/dex_bootjars/system/framework/arm64/                --instruction-set=arm64      --base-offset-delta=0x10000000 )"
dex2oat F 04-15 03:54:45  4936  4936 compiler_driver.cc:942] Had 2 soft failure(s) verifying all classes, and was asked to abort in such situations. Please check the log.
ERROR: Dex2oat failed to compile a boot image. It is likely that the boot classpath is inconsistent. Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS=--runtime-arg -verbose:verifier to see verification errors.
[  3% 62/1624] Proguard: /home/shihab_riadn/aex/out/target/common/obj/APPS/Contacts_intermediates/classes-proguard.jar
ProGuard, version 5.1
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android_stubs_current_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar]
Reading program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/Contacts_intermediates/classes.jar]
Preparing output jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/Contacts_intermediates/classes-proguard.jar]
  Copying resources from program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/Contacts_intermediates/classes.jar]
[  4% 67/1624] Proguard: /home/shihab_riadn/aex/out/target/common/obj/APPS/SystemUI_intermediates/classes-proguard.jar
ProGuard, version 5.1
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android.car_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ims-common_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/classes-header.jar]
Reading program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/SystemUI_intermediates/classes.jar]
Preparing output jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/SystemUI_intermediates/classes-proguard.jar]
  Copying resources from program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/SystemUI_intermediates/classes.jar]
[  4% 69/1624] Building Kernel
make: Entering directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /home/shihab_riadn/aex/kernel/xiaomi/markw as source for kernel
  CALL    /home/shihab_riadn/aex/kernel/xiaomi/markw/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
  CHK     include/generated/compile.h
/home/shihab_riadn/aex/kernel/xiaomi/markw/kernel/Makefile:150: *** No X.509 certificates found ***
  CHK     kernel/config_data.h
  DTC     arch/arm64/boot/dts/qcom/msm8953-qrd-markw.dtb
  CAT     arch/arm64/boot/Image.gz-dtb
make[1]: Leaving directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
Building DTBs
make: Entering directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /home/shihab_riadn/aex/kernel/xiaomi/markw as source for kernel
  CALL    /home/shihab_riadn/aex/kernel/xiaomi/markw/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
make[1]: Leaving directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
Building Kernel Modules
make: Entering directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
/home/shihab_riadn/aex/kernel/xiaomi/markw/kernel/Makefile:150: *** No X.509 certificates found ***
  Using /home/shihab_riadn/aex/kernel/xiaomi/markw as source for kernel
  CALL    /home/shihab_riadn/aex/kernel/xiaomi/markw/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
/home/shihab_riadn/aex/kernel/xiaomi/markw/kernel/Makefile:150: *** No X.509 certificates found ***
  Building modules, stage 2.
  MODPOST 0 modules
make[1]: Leaving directory '/home/shihab_riadn/aex/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/aex/kernel/xiaomi/markw'
[  4% 70/1624] Proguard: /home/shihab_riadn/aex/out/target/common/obj/APPS/messaging_intermediates/classes-proguard.jar
ProGuard, version 5.1
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/android_stubs_current_intermediates/classes-header.jar]
Reading system jar [/home/shihab_riadn/aex/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar]
Reading program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/messaging_intermediates/classes.jar]
Preparing output jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/messaging_intermediates/classes-proguard.jar]
  Copying resources from program jar [/home/shihab_riadn/aex/out/target/common/obj/APPS/messaging_intermediates/classes.jar]
ninja: build stopped: subcommand failed.
03:55:52 ninja failed with: exit status 1
build/make/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1

#### failed to build some targets (03:09 (mm:ss)) ####

**Comment by theimpulson** [comment]
Not ROM source issue. Kindly open this is issue in device specific repository or report it to your device maintainer.

**Comment by sb6596** [comment]
Fix it in your DT. Closing this issue as this is not ROM source issue.
