### ISSUE TITLE
Cannot checkout LineageOS/android_external_libexif

### ISSUE THREAD

**Issue by tripLr** [AospExtended/manifest#72]
your pie wont sync,
probably this commit
https://github.com/AospExtended/manifest/commit/99f87dd69aaebf3400fd2cdbeefa8ce8e6bf75c6
 maybe related to you changing the tracking on the lineageos source incorrectly in your manifest

Cannot checkout LineageOS/android_external_libexif: ManifestInvalidRevisionError: revision refs/heads/lineage-16.0 in LineageOS/android_external_libexif not found

Cannot fetch LineageOS/android_external_libexif from https://github.com/LineageOS/LineageOS/android_external_libexif

fatal: repository 'https://github.com/LineageOS/LineageOS/android_external_libexif/' not found
LineageOS/android_external_libexif:
remote: Not Found
fatal: repository 'https://github.com/LineageOS/LineageOS/android_external_libexif/' not found

**Comment by sb6596** [comment]
How manifest changes for Q branch will break anything on Pie branch?

**Comment by tripLr** [comment]
You posted it in the pie branch.

Go-to browser
Go-to aex in GitHub
Click manifest
Click branch and switch to 9.x
See your commit.

It totally breaks repo sync

I'm restoring my computer and havent built aex for a month.
Now I have a bunchton of devices to build.
