### ISSUE TITLE
Soong unknown variable

### ISSUE THREAD

**Issue by Niemandausduisburg** [AospExtended/manifest#77]
Hello,
when I try to build I get this error message:
[100% 183/183] /run/media/kevin/Daten/NB1/AOSPex/out/soong/.bootstrap/bin/soong_build /run/media/kevin/Daten/NB1/AOSP
FAILED: /run/media/kevin/Daten/NB1/AOSPex/out/soong/build.ninja
/run/media/kevin/Daten/NB1/AOSPex/out/soong/.bootstrap/bin/soong_build -t -l /run/media/kevin/Daten/NB1/AOSPex/out/.m
odule_paths/Android.bp.list -b /run/media/kevin/Daten/NB1/AOSPex/out/soong -n /run/media/kevin/Daten/NB1/AOSPex/out -
d /run/media/kevin/Daten/NB1/AOSPex/out/soong/build.ninja.d -globFile /run/media/kevin/Daten/NB1/AOSPex/out/soong/.bo
otstrap/build-globs.ninja -o /run/media/kevin/Daten/NB1/AOSPex/out/soong/build.ninja Android.bp
error: vendor/aosp/build/soong/Android.bp:30:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'
14:29:47 soong bootstrap failed with: exit status 1

Best regards

**Comment by ghost** [comment]
Hey Bro.
I think you need to edit vendor/aosp/build/soong/Android.bp now.
You build AEX with prebuilt kernel right ?
Annotate code：From Line 30 to the end

**Comment by ghost** [comment]
And I think you should annotate the code "generated_kernel_includes" in other files:
likes externel/tinycompress/Android.bp  .etc
maybe you need to annotate it in 4 files.

**Comment by VTVishwanath** [comment]
Could you please give detailed solution @ghost ? What are the files in which we have to edit the code? I am also facing this issue and struggling to solve the same.
