### ISSUE TITLE
Make aex not working

### ISSUE THREAD

**Issue by MightyM17** [AospExtended/manifest#78]
When I run make aex it gives an error 
`ninja: error: unknown target 'aex', did you mean 'dex'?`

**Comment by wh0dat** [comment]
Try 

mka aex

> When I run make aex it gives an error
> `ninja: error: unknown target 'aex', did you mean 'dex'?`

**Comment by MightyM17** [comment]
> Try
> 
> mka aex
> 
> > When I run make aex it gives an error
> > `ninja: error: unknown target 'aex', did you mean 'dex'?`

That still dosent work, it is because i synced with --depth=1??

**Comment by MightyM17** [comment]
mka is basically make -j$(nrpoc) xD

**Comment by wh0dat** [comment]
try brunch then

**Comment by MightyM17** [comment]
mka bacon worked :D but now its a ota file and when i flash it device reboots back to recovery :(

**Comment by sb6596** [comment]
http://gerrit.aospextended.com/c/AospExtended/manifest/+/4823
