### ISSUE TITLE
Error ("android.hardware.usb@1.2-service-qti" depends on undefined module "qti_usb_hal_supported_modes_defaults")

### ISSUE THREAD

**Issue by Bugaddr** [AospExtended/manifest#80]
While compiling aosp extended (R) for (Mido) RN4 i faced this issue https://del.dog/megnobigop.txt please provide info regarding it 

Build type - user
Device - mido

**Comment by sb6596** [comment]
Check gerrit

**Comment by enweazudaniel** [comment]
Can you share the gerrit link? @sb6596
