### ISSUE TITLE
https://www.aospextended.com/ doesn't load

### ISSUE THREAD

**Issue by oliviertassinari** [AospExtended/manifest#82]

**Comment by NagyTibor84** [comment]
It's still unavailable. Is there any way we can help to solve this?

**Comment by Lambada10** [comment]
@NagyTibor84 https://t.me/s/aospextended/2022

**Comment by oliviertassinari** [comment]
I'm closing as not planned per:

> none of us could commit ourselves to the project due to time constraints. After discussing this issue internally, we have reached a mutual decision. With a heavy heart, we are announcing today that the AospExtended project is going on an **indefinite hiatus**.

https://t.me/s/aospextended/2022
